---
abstract: 'PerlIO layer for length restrictions'
author:
  - 'WATANABE Hiroaki <hwat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlIO-via-Limit
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Class::Data::Inheritable: 0
  Exception::Class: 0
  PerlIO::via: 0
  Test::More: 0.32
resources:
  bugtracker: https://github.com/hiroaki/PerlIO-via-Limit/issues
  homepage: https://github.com/hiroaki/PerlIO-via-Limit
  repository: https://github.com/hiroaki/PerlIO-via-Limit.git
version: 0.04
x_contributors:
  - 'WATANABE Hiroaki <hwat@mac.com>'
